apiVersion: apps/v1
kind: Deployment
metadata:
  name: solution-master
  labels:
    app.kubernetes.io/name: solution
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.replicas.master }}
  selector:
    matchLabels:
      app.kubernetes.io/name: solution
  template:
    metadata:
      labels:
        app.kubernetes.io/name: solution
    spec:
      containers:
        - name: solution
          image: {{ $image }}
          env:
            - name: ROLE
              value: "register"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solution-worker
  labels:
    app.kubernetes.io/name: solution
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.replicas.worker }}
  selector:
    matchLabels:
      app.kubernetes.io/name: solution
  template:
    metadata:
      labels:
        app.kubernetes.io/name: solution
    spec:
      containers:
        - name: solution
          image: {{ $image }}
          env:
            - name: ROLE
              value: "worker"
