---
global:
  storageClass: "default"  # 存储类名称

kafka:
  replicas: 3  # Kafka 副本数量
  persistence:
    enabled: true  # 启用持久化存储
    size: 10Gi  # 持久化存储大小
  zookeeper:
    persistence:
      enabled: true  # 启用持久化存储
      size: 5Gi  # 持久化存储大小
