apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      nodeSelector:
        Deployment: dev
      containers:
        - name: ${env.CONTAINER_NAME.replace('_', '-')}
          image: docker/kafka-producer:lastest
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "Asia/Shanghai"
                       // 定义Service配置
  apiVersion: v1
  kind: Service
  metadata:
    name: kafka-producer
  spec:
    selector:
      app: kafka-producer
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 8080
        nodePort: 30000
    type: NodePort